### ISSUE TITLE
Add callback function for angular controller

### ISSUE THREAD

**Issue by arryon** [diegopamio/angular-sails-bind#22]
The standard method of loading content using $http in Angular has the option to specify a success callback when the content has loaded, so that in the controller, you can initiate scope bindings dependent on data.
The angular-sails-bind directive has no such thing. I implemented it myself in https://github.com/arryon/angular-sails-bind/commit/0ec49070f32bce1c384d023d5f5781b1fdc76528 but probably there is a better way to do this, like the default .success() and .error() paradigm. Any ideas?

**Comment by spunkedy** [comment]
I have solved this by adding a $watch to the object and passing a function to the watch.

**Comment by diegopamio** [comment]
I've merged your changes from your fork to do it, thanks!
