### ISSUE TITLE
N-to-N items

### ISSUE THREAD

**Issue by rmckeel** [diegopamio/angular-sails-bind#29]
I'm testing Angular Sails Bind, and it is really close to being super powerful in my app.  I'm wondering if there is a way (or if it should) work off sub-items.  That is, imagine I have A's and B's with an N-to-N relationship.  I query for one A and get it back, and it has three B's attached to it.  If I could watch items in B and manipulate them, it would be super powerful.  I imagine others would have a benefit with this also.

Is this a good feature request?  Useful?  Doable?

Thanks,

  Ryan

**Comment by diegopamio** [comment]
#11 discusses that. I'm not sure how to implement a good solution on that. Any help will be welcome.
