### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by TomKaltz** [diegopamio/angular-sails-bind#30]
Would be great to have this on npm.

**Comment by diegopamio** [comment]
Do you know how to do it? It is currently in bower, are you using npm instead? Even for browser-related libraries?

**Comment by TomKaltz** [comment]
Yes, I use browserify and had to modify the package.json to make it work
properly.  I will submit a PR if I can find some time soon.

**Comment by diegopamio** [comment]
Do you know what else needs to be done?

**Comment by apinnecke** [comment]
http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

This is an exact description of what needs to be done.

**Comment by apinnecke** [comment]
I closed #35 and opened #36, which also contains two new socket events as well as the required index.js described in the link i posted. So merging #36 would make this package usable for browserify. :)

**Comment by Schubidu** [comment]
:+1:

**Comment by diegopamio** [comment]
Done! it's on NPM! :)
