### ISSUE TITLE
Weird pagination

### ISSUE THREAD

**Issue by maikelohcfg** [diegopamio/angular-sails-bind#37]
hello there 

i used  

$sailsBind.bind("resource", $scope);

in my project to listen to realtime updates via socket of resource model, but it only display the first 30 records, like it was paginating the results. This a default behavior or some king of pagination that sails do??

**Comment by 0x5e5e** [comment]
Hi @maikelohcfg,

You probably don't care about the solution anymore, but in case you were still interested - this is a server-side setting in Sails in `config/blueprints.js `  called `defaultLimit`  which defaults to exactly 30 records.   Modify that value to whatever you need (-1 brings up all records) .

**Comment by maikelohcfg** [comment]
thanks a lot for the answer i will take in consideration
